### ISSUE TITLE
Navbar non aggiornata rispetto al mockup nel master branch

### ISSUE THREAD

**Issue by ludovicobesana** [Coding-Bunker/official-website#56]
<img width="1668" alt="navbar" src="https://user-images.githubusercontent.com/35035423/102936718-f2955700-44a8-11eb-9a3e-355c9652bea4.png">

**Comment by Baraff24** [comment]
Aggiornamento completato

**Comment by Nabster101** [comment]
il margin left della navbar non va bene, il bottone entra nel bunker appare al centro

**Comment by Baraff24** [comment]
Aggiornata, sto finendo di aggiornare lato mobile
